### ISSUE TITLE
Comments in the repository

### ISSUE THREAD

**Issue by bitrecluse** [dawnbomb/Crystal-Editor#8]
#1 

I think a goal should be to minimize comments as much as possible. 
Why remove something that seems so useful you may ask?

Well IMO if a dev is spending time writing blobs of green text then they have not spent the time to truly refine the object they are working on (Class, Method, Function, Enum, etc.)

Naming things in this field is extremely difficult, why? because that's what matters. When a dev hits whatever shortcut they hit to get to this random method that's causing them grief, they do not want to find the other portion of the codebase that has keys to the door of knowledge, they want the method name to tell them succinctly what the method is doing since that is exactly what is causing the issue at hand.

This of course is not meant as an insult but to be taken as maybe that portion of the code is simply just not ready for the _master_ branch and belongs in more of an experimental one or like a pre-build/staged/ something that can legit be broken and no one cares at all while these tiny details get worked out so that all contributors can understand the code immediately as best as possible.

After all users can choose what branch/release to go with while the repository maintainers continually/gingerly mold the repo into something concrete and concise.

**Comment by dawnbomb** [comment]
i literally just read the first line and went "no".
i am not so stupid as to think i can handle my first project without writing notes. I also write notes to keep track of my thought process at the time, so later on i can understand exactly why that was thought that way, and contest it. I have literally never heard of people saying not to write comments / notes before. 

Let me be very clear here....i expect notes to not disappear without proper explanation as to why. They can be remade, simplified, etc, but if they aren't detailed enough that someone can understand whats going on, then thats a no go. As it stands, i already think the codebase needs more notes not less. while some of them could be removed, there are plenty of places that can use 2-3 lines of descriptive text to make sure everyone (myself included) is following along.

Seperate (entirely seperately) if you have suggestions for names of things to be renamed, go for it. I went through 2 big rename efforts during my project, where each time i took like 3 days just renaming absolutely everything now that i had a better understanding of how everything wants to be. I make stuff, then change my mind and use it in a different way, then again. Part of why the project isn't open, the "Forward compatibility project" in a 4 part effort, to change how some aspects of it work yet again, and yet again stuff will get renamed and changed. 

However...detailed comments about how things *used to be* is also useful, to realize that the usage of something has changed and it was forgotten about, and to re-evaluate it.

**Comment by bitrecluse** [comment]
First line is problem number one and that makes every Repo _die_ like over and over and over again

**Comment by dawnbomb** [comment]
Wel then, allow me to be a stupid newbie and again, just say no.

I like comments, they help me remember stuff, and explain stuff. You hate comments, i like comments.

**Comment by bitrecluse** [comment]
This is _extremely_ useful information to developers. Please keep this in mind when discussing issue #2

**Comment by bitrecluse** [comment]
There are indeed great places for comments in code. Links to information, spots in code where you had to work especially hard to code around a very specific bug, that type of thing.
However this is really about _noise_. You see the more noise in your code base the more just generally confusing it becomes.
I think once you get the hang of the issues section and how it all links up to your code and how it sort of becomes its own like internal developer _wiki_ you will rely less on comments.

**Comment by dawnbomb** [comment]
this will not be a wiki, this is you throwing a temper tantrum. if a wiki exists for code, it will be separate. Issues are supposed to be for actual *issues* with the program, not your personal soap box of you craftily saying that you don't like me being new and don't want me having comments all over. You didn't actually show off any examples of simplifying comments or anything of the sort, so its easy for me to reject.

**Comment by bitrecluse** [comment]
i pointed you to the folks who made all of this stuff you are using yet still think is wrong. They have all of the best examples. I also gave you a link to a very well run youtube channel by the name of IamTimCorey and told you how I had learned a great deal from there

**Comment by bitrecluse** [comment]
> it will be separate. Issues are supposed to be for actual issues with the program
This is also very great info to keep in mind regarding issue #2

**Comment by dawnbomb** [comment]
At this point, your just ingoring what im saying, not talking about comments anymore, not showing any examples, and making up stuff that never happened about links (about comments?) and continuing to tell me im wrong for having comments in my code. 

i am closing this topic as your mentally uncapable of following your own conversation.
